In [5]:
import numpy as np
import pandas as pd

### Q1 - numpy version

In [3]:
np.__version__

'1.21.2'

In [11]:
!pip freeze | grep numpy | tr -d "numpy=="

1.21.2


### Q2 pandas version

In [7]:
pd.__version__

'1.3.2'

In [10]:
!pip freeze | grep pandas | tr -d "pandas=="

1.3.2


#### (down)loading source data

In [15]:
!curl https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv --output car-data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1440k  100 1440k    0     0  3335k      0 --:--:-- --:--:-- --:--:-- 3327k


In [16]:
! ls -l

total 6104
-rw-r--r--   1 abarabas  staff  1475504 Sep 11 14:54 car-data.csv
-rw-r--r--   1 abarabas  staff  1643092 Sep 11 14:53 hw1.ipynb
drwxr-xr-x  23 abarabas  staff      736 Sep 11 12:13 mlbookcamp-code


In [18]:
!head -5 car-data.csv

Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
BMW,1 Series M,2011,premium unleaded (required),335,6,MANUAL,rear wheel drive,2,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
BMW,1 Series,2011,premium unleaded (required),300,6,MANUAL,rear wheel drive,2,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
BMW,1 Series,2011,premium unleaded (required),300,6,MANUAL,rear wheel drive,2,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
BMW,1 Series,2011,premium unleaded (required),230,6,MANUAL,rear wheel drive,2,"Luxury,Performance",Compact,Coupe,28,18,3916,29450


In [23]:
DATA_FILE="./car-data.csv"
df = pd.read_csv(DATA_FILE, header=0, sep=",")

In [24]:
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Q3 - average price of BMWs

In [55]:
# some data cleansing, maybe not necessary in case of BMWs :)
df["Make"] = df["Make"].str.upper().str.strip()

In [56]:
df[df["Make"]=="BMW"].MSRP.mean()

61546.76347305389

### Q4 - missing engine HP for cars since 2015 

In [71]:
df[df["Year"]>=2015]["Engine HP"].isna().sum()

51

### Q5 - Engine HP

In [77]:
avg_hp_before = df["Engine HP"].mean()
avg_hp_before

249.38607007176023

In [78]:
avg_hp_after = df["Engine HP"].fillna(avg_hp_before).mean()
avg_hp_after

249.38607007176023

In [79]:
if round(avg_hp_after) == round(avg_hp_before):
    print("There was no change between 'before' and 'after'")
else:
    print("There was a change between in Engine HP")

There was no change between 'before' and 'after'


### Q6 - matrix operations on RollsRoyce

In [86]:
#all Rolls Royces
df[df["Make"]== "ROLLS-ROYCE"]

Make                   Model  Year             Engine Fuel Type  \
2921   ROLLS-ROYCE                Corniche  2001  premium unleaded (required)   
3505   ROLLS-ROYCE                    Dawn  2016  premium unleaded (required)   
5275   ROLLS-ROYCE         Ghost Series II  2015  premium unleaded (required)   
5276   ROLLS-ROYCE         Ghost Series II  2015  premium unleaded (required)   
5277   ROLLS-ROYCE         Ghost Series II  2016  premium unleaded (required)   
5278   ROLLS-ROYCE         Ghost Series II  2016  premium unleaded (required)   
5279   ROLLS-ROYCE                   Ghost  2012  premium unleaded (required)   
5280   ROLLS-ROYCE                   Ghost  2012  premium unleaded (required)   
5281   ROLLS-ROYCE                   Ghost  2013  premium unleaded (required)   
5282   ROLLS-ROYCE                   Ghost  2013  premium unleaded (required)   
5283   ROLLS-ROYCE                   Ghost  2014  premium unleaded (required)   
5284   ROLLS-ROYCE                   Ghost  2014  premium unleaded (required)   
7443   ROLLS-ROYCE               Park Ward  2001  premium unleaded (required)   
7444   ROLLS-ROYCE               Park Ward  2002  premium unleaded (required)   
7553   ROLLS-ROYCE           Phantom Coupe  2014  premium unleaded (required)   
7554   ROLLS-ROYCE           Phantom Coupe  2015  premium unleaded (required)   
7555   ROLLS-ROYCE           Phantom Coupe  2016  premium unleaded (required)   
7556   ROLLS-ROYCE  Phantom Drophead Coupe  2014  premium unleaded (required)   
7557   ROLLS-ROYCE  Phantom Drophead Coupe  2015  premium unleaded (required)   
7558   ROLLS-ROYCE  Phantom Drophead Coupe  2016  premium unleaded (required)   
7559   ROLLS-ROYCE                 Phantom  2014  premium unleaded (required)   
7560   ROLLS-ROYCE                 Phantom  2014  premium unleaded (required)   
7561   ROLLS-ROYCE                 Phantom  2015  premium unleaded (required)   
7562   ROLLS-ROYCE                 Phantom  2015  premium unleaded (required)   
7563   ROLLS-ROYCE                 Phantom  2016  premium unleaded (required)   
7564   ROLLS-ROYCE                 Phantom  2016  premium unleaded (required)   
9431   ROLLS-ROYCE           Silver Seraph  2001  premium unleaded (required)   
9432   ROLLS-ROYCE           Silver Seraph  2002  premium unleaded (required)   
11448  ROLLS-ROYCE                  Wraith  2014  premium unleaded (required)   
11449  ROLLS-ROYCE                  Wraith  2015  premium unleaded (required)   
11450  ROLLS-ROYCE                  Wraith  2016  premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921       325.0               8.0         AUTOMATIC  rear wheel drive   
3505       563.0              12.0         AUTOMATIC  rear wheel drive   
5275       563.0              12.0         AUTOMATIC  rear wheel drive   
5276       563.0              12.0         AUTOMATIC  rear wheel drive   
5277       563.0              12.0         AUTOMATIC  rear wheel drive   
5278       563.0              12.0         AUTOMATIC  rear wheel drive   
5279       563.0              12.0         AUTOMATIC  rear wheel drive   
5280       563.0              12.0         AUTOMATIC  rear wheel drive   
5281       563.0              12.0         AUTOMATIC  rear wheel drive   
5282       563.0              12.0         AUTOMATIC  rear wheel drive   
5283       563.0              12.0         AUTOMATIC  rear wheel drive   
5284       563.0              12.0         AUTOMATIC  rear wheel drive   
7443       322.0              12.0         AUTOMATIC  rear wheel drive   
7444       322.0              12.0         AUTOMATIC  rear wheel drive   
7553       453.0              12.0         AUTOMATIC  rear wheel drive   
7554       453.0              12.0         AUTOMATIC  rear wheel drive   
7555       453.0              12.0         AUTOMATIC  rear wheel drive   
7556       453.0              12.0         AUTOMATIC  rear wheel drive   
7557       453.

In [89]:
# only selected columns
rrdf = df[df["Make"]== "ROLLS-ROYCE"][["Engine HP", "Engine Cylinders", "highway MPG"]]
rrdf

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [92]:
rrdf_dedup =rrdf.drop_duplicates()
rrdf_dedup

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [105]:
#getting np array
X=rrdf_dedup.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [113]:
X_T = X.T
XTX = X_T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [114]:
np.matmul(X_T,X)

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [115]:
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [116]:
XTX_inv.sum()

0.032212320677486125

### Q7

In [122]:
y=np.array([1000,1100,900,1200,1000,850,1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [128]:
w = (np.matmul(np.linalg.inv(XTX), X_T)).dot(y)
print(f"w:{w}\n")
print(f"first  element of w: {w[0]} ")

w:[ 0.19989598 31.02612262 31.65378877]

first  element of w: 0.19989598183188972 
